<?php
/*
*
* (c) Marco Bunge <marco_bunge@web.de>
*
* For the full copyright and license information, please view the LICENSE.txt
* file that was distributed with this source code.
*
* Date: 22.11.2015
* Time: 14:28
*/

namespace Blast\Tests\Orm;


use Blast\Orm\Model\ModelInterface;
use Blast\Orm\Repository\Repository;
use PHPUnit_Framework_TestCase;
use Prophecy\Prophecy\ObjectProphecy;

class FunctionalTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ObjectProphecy
     */
    private $model = null;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->model = $this->prophesize(ModelInterface::class);
        $this->model->willImplement(ModelInterface::class);
    }


    public function testFunctional()
    {
        $posts = $this->model->reveal();
        $comments = $this->model->reveal();
        $tags = $this->model->reveal();

        //configure repository
        $repository = new Repository([
            'posts' => $posts,
        ]);

        //add entity to repository
        $repository->add('tags', $tags);

        //get mapper and add automatically
        $repository->mapper($comments, 'comments');

        //get mapper from locator
        //locator
        $locator = Locator::create([]);
        $locator->mapper($entity);

        $locator->repository();





    }
}
